name: "Supabase Anti-Pause Agent 😋😋"

on:
  schedule:
    # Ejecutar cada 12 horas (00:00 y 12:00 UTC)
    - cron: '0 */12 * * *' 
  workflow_dispatch: # Permite probarlo manualmente desde GitHub

jobs:
  simulate_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Stealth Script
        env:
          # Forzamos esta URL como el "botón de encendido" principal
          TARGET_URL: 'https://balconesdeparaguana1.vercel.app/login/'
        run: python scripts/keeper.py